<b>Exercise:</b>
1. Create a 6x4 array, which includes random integers from 1 to 10, name this array "A". print the array A.
2. Find all the numbers bigger than 5 and multiply them with 10, name this new array B.
3. Replace the element on the 2nd row, 3rd column of B, with -10 

In [1]:
import numpy as np
!pip install pipe
from pipe import select, where

Defaulting to user installation because normal site-packages is not writeable


In [2]:
# step-1
A = np.random.randint(1,11,24).reshape(6,4)
print(A)

[[10  1  7  9]
 [ 9  4  7  1]
 [ 9  8  7  5]
 [ 7  5  8  5]
 [ 1  9  5  8]
 [ 6  9  8  2]]


In [3]:
# step-2: Method-1: Old-fashion
B = np.copy(A)
for i in range(len(A)):
  for j in range(len(A[0])):
    if A[i,j]>5:
      B[i,j] = 10*A[i,j] 
print(B)      

[[100   1  70  90]
 [ 90   4  70   1]
 [ 90  80  70   5]
 [ 70   5  80   5]
 [  1  90   5  80]
 [ 60  90  80   2]]


In [4]:
# step-2: Method-2: One For Loop
inda = np.asarray(np.where(A>5))
B = np.copy(A)
for i in range(int(inda.size/2)):
  B[inda[0,i],inda[1,i]] = 10*A[inda[0,i],inda[1,i]]
print(B)  

[[100   1  70  90]
 [ 90   4  70   1]
 [ 90  80  70   5]
 [ 70   5  80   5]
 [  1  90   5  80]
 [ 60  90  80   2]]


In [5]:
# step-2: Method-3: Numpy's Select (https://numpy.org/doc/stable/reference/generated/numpy.select.html)
B = np.select([A<=5, A>5], [A, A*10])
print(B)

[[100   1  70  90]
 [ 90   4  70   1]
 [ 90  80  70   5]
 [ 70   5  80   5]
 [  1  90   5  80]
 [ 60  90  80   2]]


In [6]:
# step-2: Method-4: Proper use of "where"
B = A.copy()
ind1, ind2 = np.where(A>5.0)
B[ind1,ind2] = B[ind1,ind2]*10
print(B)

[[100   1  70  90]
 [ 90   4  70   1]
 [ 90  80  70   5]
 [ 70   5  80   5]
 [  1  90   5  80]
 [ 60  90  80   2]]


In [7]:
# step-2 Method-5 (Pipe + Lambda)
B = np.array(list(A.flatten().tolist()| select(lambda x: 10*x if x>5 else x))).reshape(6,4)
print(B)

[[100   1  70  90]
 [ 90   4  70   1]
 [ 90  80  70   5]
 [ 70   5  80   5]
 [  1  90   5  80]
 [ 60  90  80   2]]


In [8]:
# step-2: Method-6: zip-method
B = np.array([j*10 if i else j for i,j in 
               zip((A > 5).flatten(), A.flatten())]).reshape((6,4))
print(B)

[[100   1  70  90]
 [ 90   4  70   1]
 [ 90  80  70   5]
 [ 70   5  80   5]
 [  1  90   5  80]
 [ 60  90  80   2]]


In [9]:
# step-3
B[1,2] = -10
print(B)

[[100   1  70  90]
 [ 90   4 -10   1]
 [ 90  80  70   5]
 [ 70   5  80   5]
 [  1  90   5  80]
 [ 60  90  80   2]]


# Notebook End